services:
  mongodb:
    image: mongo:latest
    container_name: cointrack-mongodb
    environment:
      - MONGO_INITDB_DATABASE=mydatabase
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  api:
    build: .
    container_name: cointrack-api
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://root:secret@mongodb:27017/mydatabase?authSource=admin
    ports:
      - "8080:8080"

volumes:
  mongodb_data:
